### PR TITLE
Local phishing attack using SimpleHTTPserver and DNS-Spoofing. 

### PR DESCRIPTION
**Pull request by SkiddieTech**
My first payload contribution for the Packet Squirrel platform.
Phishing attack using DNS-Spoofing and SimpleHTTPServer.

### CODE REVIEW

**Comment by infoskirmish** [comment]
What happens after a target enters in their login data?

**Comment by SkiddieTech** [comment]
@infoskirmish the login data is sent as a GET request to a file called "loading.html" inside the same folder, this is so the SimpleHTTPServer log data can pick it up and store it in loot.txt.

Short, its saved in loot.txt

**Comment by sundhaug92** [comment]
Could you change the title (both "Payload" and "Phishing") to something more descriptive?

**Comment by infoskirmish** [comment]
@SkiddieTech Sorry for the delay in response. Sounds awesome. Yes the Packet Squirrel is pretty awesome but it also has some limitations. I am surprised there is no gpg support and more free onboard memory. Memory is cheap and chips are small. Anyhow I digress. 

What about this... instead of trying to pass off the creds why not direct to an "oops page" kind of like this:
http://www.technotipsblog.com/2010/10/what-is-meant-by-google-oops.html

With a real link to the actual page?

**Comment by SkiddieTech** [comment]
@infoskirmish good suggestion, il update "loading.html"

**Comment by sebkinne** [comment]
@SkiddieTech we don't condone phishing Google / Twitter / Facebook / Banking / etc credentials. If you make this payload more generic I'd be happy to accept it though.

**Pull request closed without merging**
