### PR TITLE
I Hate Wifi

### PR DESCRIPTION
**Pull request by TheDragonkeeper**
De-authentication of all clients on all APs in your area

### CODE REVIEW

**Comment by thehappydinoa** [comment]
So I think everything looks pretty good, but would you be able to make a options section in the readme and payload.sh

**Comment by sundhaug92** [comment]
One issue: This fails without warning if there's no access to the opkg-repos.

**Comment by TheDragonkeeper** [comment]
Added extra into the file check so user is alerted of failures.

thehappydinoa  (unsure what you mean by 'options section', so) i added in a part to let the user know what to change.

**Comment by thehappydinoa** [comment]
@TheDragonkeeper That was exactly what I was talking about.

**Comment by Dave-ee** [comment]
Any documentation of what WiFi adapter is recommended, and what adapters are supported?

**Comment by sundhaug92** [comment]
@Dave-ee That info is in the changelog for 1.1

**Pull request merged**
