### PR TITLE
Added -s 0 so tcpdump doesn't truncate packets

### PR DESCRIPTION
**Pull request by cdhop**

### CODE REVIEW

**Comment by sundhaug92** [comment]
Isn't this the default for recent versions of tcpdump?

**Comment by cdhop** [comment]
No, Based on the documentation found here: https://www.tcpdump.org/tcpdump_man.html

Before adding it I found incomplete files when I used Wireshark, afterwards not so much

**Comment by sundhaug92** [comment]
Strange. 

> Snarf snaplen bytes of data from each packet rather than the default of 262144 bytes... Setting snaplen to 0 sets it to the default of 262144

**Comment by sebkinne** [comment]
Thanks for the PR @cdhop !

**Pull request merged**
