### PR TITLE
Nmapdump

### PR DESCRIPTION
**Pull request by infoskirmish**
This payload will scan a network with nmap; try to resolves some common problems if encountered.

### CODE REVIEW

**Comment by elgplayer** [comment]
Maybe change the category from sniffing to recon?

**Comment by infoskirmish** [comment]
Good idea. However I'll let the admins decide how they wish to organize the library. :) I just placed it in sniffers since it uses a bunch of sniffing apps but I agree overall recon would be a more appropriate category for this payload.

**Comment by thehappydinoa** [comment]
@infoskirmish I put this in recon, mainly because it doesn't actually sniff and record packets. It just scans for IPs

**Comment by infoskirmish** [comment]
@thehappydinoa thank you. @elgplayer Sorry, when I read your comment I was on the go. I misread what payload you were commenting on and mistakenly read it as another payload I have submitted which only uses a bunch of sniffers.... anyhow. Yes, I agree, this payload is better described as a recon tool.

**Comment by infoskirmish** [comment]
@thehappydinoa thanks for your help on how to split these up into different pull requests. I am slowly getting the hang of this github thing.

**Comment by sebkinne** [comment]
@infoskirmish if you change the top-folder to recon I'll gladly accept this PR.

**Comment by infoskirmish** [comment]
@sebkinne Done!

**Pull request merged**
